include: package:lint/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    prefer_asserts_in_initializer_lists: false

analyzer:
  errors:
    todo: info
    
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
